#!/bin/bash
../../../lazarus/tools/lazres ../source/codebot_controls_design/palette_icons.res \
	TImageStrip.bmp \
	TRenderImage.bmp \
	TRenderBox.bmp \
	TSlideBar.bmp \
	TThinButton.bmp \
	TIndeterminateProgress.bmp \
	THuePicker.bmp \
	TSaturationPicker.bmp \
	TBanner.bmp \
	TContentGrid.bmp \
	TSizingPanel.bmp \
	THeaderBar.bmp \
	TDrawList.bmp \
	TDrawTextList.bmp \
	TDetailsList.bmp \
	TExternalCommand.bmp
