#!/bin/bash
../../../lazarus/tools/lazres ../source/codebot_controls_design/palette_icons.res \
	TImageStrip.bmp \
	TSlideBar.bmp \
	TThinButton.bmp \
	TDrawImage.bmp \
	TDrawBox.bmp \
	TDrawPanel.bmp \
	TIndeterminateProgress.bmp \
	TStepBubbles.bmp \
	THuePicker.bmp \
	TSaturationPicker.bmp \
	TAlphaPicker.bmp \
	TAnglePicker.bmp \
	TBanner.bmp \
	TContentGrid.bmp \
	TSizingPanel.bmp \
	TCaptionBox.bmp \
	THeaderBar.bmp \
	TDrawList.bmp \
	TDrawTextList.bmp \
	TDetailsList.bmp \
	TAnimationTimer.bmp \
	TTextStorage.bmp \
	TSlideEdit.bmp \
	TColorSlideEdit.bmp \
	TAdvancedColorDialog.bmp \
	TExternalCommand.bmp
