(********************************************************)
(*                                                      *)
(*  Codebot Pascal Library                              *)
(*  http://cross.codebot.org                            *)
(*  Modified October 2026                               *)
(*                                                      *)
(********************************************************)

{ <include docs/codebot.webkit.controls.txt> }
unit Codebot.WebKit.Controls;

{$i webkit.inc}

interface

uses
  Classes, SysUtils, Graphics, Controls, LMessages, LCLType,
  Codebot.WebKit.Controls.Gtk3;

type
  TWebHitTestItem = (
    { Mouse is over a hyper link }
    htLink,
    { Mouse is over an image element }
    htImage,
    { Mouse is over an audio or video element }
    htMedia,
    { Mouse is over selected text or other selected elements }
    htSelection,
    { Mouse is over an area where the user can type }
    htEditable);
  TWebHitTest = set of TWebHitTestItem;

  TWebNavigateAction = (
    { Allow the browser to follow a navigation }
    naAllow,
    { Block the browser from following a navigation }
    naDeny);

  TWebLoadStatus = (
    { Nothing has been loaded }
    lsNone,
    { Load started but may fail }
    lsStarted,
    { Load was redirected to another uri }
    lsRedirected,
    { Load has received the first response }
    lsCommitted,
    { Load is complete }
    lsFinished,
    { Load stopped with an error }
    lsFailed);

  TWebScriptDialog = (
    { Javascript asked to display an alert message }
    sdAlert,
    { Javascript asked to confirm an action }
    sdConfirm,
    { Javascript asked to prompt for a value }
    sdPrompt);

  TWebNotify = (
    { The web view of a browser was created }
    wnReady,
    { The location of a browser changed }
    wnLocation,
    { The title of a browser changed }
    wnTitle,
    { The progress of a load changed }
    wnProgress,
    { The status of a load changed }
    wnLoadStatus,
    { The link under the mouse changed }
    wnHover,
    { A download started, progressed, or finished }
    wnDownload);

{ TWebNotifyEvent is used by other controls to listen to changes in a browser }

  TWebNotifyEvent = procedure(Sender: TObject; Notify: TWebNotify) of object;
  TWebNotifyEvents = array of TWebNotifyEvent;

{ Error events allow you to examine errors that occur during a load. Stopping
  a load or denying a navigation are also reported as errors.
  Set Handled to True to prevent the default error page. }
  TWebErrorEvent = procedure(Sender: TObject; const Uri: string; ErrorCode: Integer;
    const ErrorMessage: string; var Handled: Boolean) of object;
{ Context menu events occur before a context menu is shown. X and Y are -1
  when the menu was requested using the keyboard.
  Set Handled to True to prevent the default menu. }
  TWebContextMenuEvent = procedure(Sender: TObject; X, Y: Integer;
    HitTest: TWebHitTest; const Link, Media: string; var Handled: Boolean) of object;
{ Hit testing allows you to determine the element under the mouse.
  Link refers to the uri under the mouse, and Media refers to the element source. }
  TWebHitTestEvent = procedure(Sender: TObject; HitTest: TWebHitTest;
    const Link, Media: string) of object;
{ Before a uri can be navigated you can allow or deny it access.
  Set Action to alter the access. }
  TWebNavigateEvent = procedure(Sender: TObject; const Uri: string;
    var Action: TWebNavigateAction) of object;
{ Progress ranges from 0 to 100 in terms of a percentage of completion }
  TWebProgressEvent = procedure(Sender: TObject; Progress: Integer) of object;
{ Script dialog events are generated by javascript on a page. The actual dialog
  is shown by the default handler of TCustomWebBrowser, but you can override
  that functionality. }
  TWebScriptDialogEvent = procedure(Sender: TObject;
    { The dialog type, either alert, confirm, or prompt }
    Dialog: TWebScriptDialog;
    { The message displayed in the body of the dialog }
    const Message: string;
    { For prompt dialogs this holds the default value and receives the result value }
    var Input: string;
    { Set Accepted to True if the user clicks OK to close the dialog }
    var Accepted: Boolean;
    { Set Handled to True to prevent the default dialog handler }
    var Handled: Boolean) of object;

  TWebDownloadStatus = (
    { The download is in progress }
    dsActive,
    { The download completed }
    dsFinished,
    { The download stopped with an error or was cancelled }
    dsFailed);

{ TWebDownload is a file downloaded by a browser }

  TWebDownload = class
  private
    FHandle: Pointer;
    FUri: string;
    FFileName: string;
    FProgress: Integer;
    FStatus: TWebDownloadStatus;
    FErrorMessage: string;
  public
    { The uri the file is downloaded from }
    property Uri: string read FUri;
    { The name of the file being written }
    property FileName: string read FFileName;
    { The progress of the download ranging from 0 to 100 }
    property Progress: Integer read FProgress;
    property Status: TWebDownloadStatus read FStatus;
    { The reason the download failed }
    property ErrorMessage: string read FErrorMessage;
  end;

{ A download start event occurs before a file is downloaded. FileName is the
  name of the file to write and can be changed.
  Set Allow to False to prevent the download. }
  TWebDownloadStartEvent = procedure(Sender: TObject; const Uri: string;
    var FileName: string; var Allow: Boolean) of object;
{ Download events occur as a download progresses and when it finishes or fails }
  TWebDownloadEvent = procedure(Sender: TObject; Download: TWebDownload) of object;

{ TCustomWebBrowser is an embeddable web browser control.

  The control hosts a WebKitGTK web view once its window is created. Changes
  made before then, such as setting Location, are kept and applied when the
  window is created. If the WebKitGTK library is not installed the control
  paints the WebKit logo and a message instead, which can be checked using the
  Available function.

  Nothing is loaded at design time, where the control paints the WebKit logo. }

  TWebInspector = class;

  TCustomWebBrowser = class(TWinControl, IWebBrowserEvents)
  private
    FLocation: string;
    FHtml: string;
    FHtmlDefined: Boolean;
    FTitle: string;
    FLoadStatus: TWebLoadStatus;
    FProgress: Integer;
    FEditable: Boolean;
    FZoomFactor: Double;
    FZoomTextOnly: Boolean;
    FDeveloperTools: Boolean;
    FHoverLink: string;
    FListeners: TWebNotifyEvents;
    FCanvas: TControlCanvas;
    FInspector: TWebInspector;
    FDownloads: TList;
    FDownloadFolder: string;
    FOnDownloadStart: TWebDownloadStartEvent;
    FOnDownloadProgress: TWebDownloadEvent;
    FOnDownloadFinish: TWebDownloadEvent;
    FOnError: TWebErrorEvent;
    FOnContextMenu: TWebContextMenuEvent;
    FOnHitTest: TWebHitTestEvent;
    FOnLoadStatusChange: TNotifyEvent;
    FOnLocationChange: TNotifyEvent;
    FOnTitleChange: TNotifyEvent;
    FOnNavigate: TWebNavigateEvent;
    FOnProgress: TWebProgressEvent;
    FOnScriptDialog: TWebScriptDialogEvent;
    function GetLoading: Boolean;
    function GetDownloadCount: Integer;
    function GetDownload(Index: Integer): TWebDownload;
    function FindDownload(Handle: Pointer): TWebDownload;
    procedure SetInspector(Value: TWebInspector);
    function IsZoomFactorStored: Boolean;
    procedure Notify(Kind: TWebNotify);
    procedure SetLocation(const Value: string);
    procedure SetEditable(Value: Boolean);
    procedure SetZoomFactor(Value: Double);
    procedure SetZoomTextOnly(Value: Boolean);
    procedure SetDeveloperTools(Value: Boolean);
    procedure WMPaint(var Message: TLMPaint); message LM_PAINT;
    { IWebBrowserEvents }
    procedure ViewLoadChange(LoadEvent: Integer);
    procedure ViewError(const Uri: string; ErrorCode: Integer; const ErrorMessage: string;
      var Handled: Boolean);
    procedure ViewProgress(Progress: Integer);
    procedure ViewLocationChange(const Uri: string);
    procedure ViewTitleChange(const Title: string);
    procedure ViewNavigate(const Uri: string; var Allow: Boolean);
    procedure ViewHitTest(Context: LongWord; const Link, Media: string);
    procedure ViewContextMenu(X, Y: Integer; Context: LongWord; const Link, Media: string;
      var Handled: Boolean);
    procedure ViewScriptDialog(Dialog: Integer; const Message: string;
      var Input: string; var Accepted: Boolean);
    procedure ViewDownloadStart(Download: Pointer; const Uri: string;
      var FileName: string; var Allow: Boolean);
    procedure ViewDownloadProgress(Download: Pointer; Progress: Integer);
    procedure ViewDownloadFinish(Download: Pointer; Failed: Boolean;
      const ErrorMessage: string);
    procedure ViewInspectorRequest(var Hosted: Boolean);
    procedure InspectorRequestAsync(Data: PtrInt);
  protected
    class procedure WSRegisterClass; override;
    procedure InitializeWnd; override;
    procedure DestroyWnd; override;
    procedure Notification(AComponent: TComponent; Operation: TOperation); override;
    procedure PaintWindow(DC: HDC); override;
    procedure Paint; virtual;
    { HasView is true when the control hosts a web view, and false when it
      paints itself }
    function HasView: Boolean;
    { ControlCanvas is used to paint the control when it has no web view }
    property ControlCanvas: TControlCanvas read FCanvas;
    { The methods below are called in response to changes in the web view }
    procedure DoLoadStatus(Status: TWebLoadStatus); virtual;
    procedure DoError(const Uri: string; ErrorCode: Integer; const ErrorMessage: string;
      var Handled: Boolean); virtual;
    procedure DoProgress(Progress: Integer); virtual;
    procedure DoLocationChange(const Uri: string); virtual;
    procedure DoTitleChange(const Title: string); virtual;
    procedure DoNavigate(const Uri: string; var Action: TWebNavigateAction); virtual;
    procedure DoHitTest(HitTest: TWebHitTest; const Link, Media: string); virtual;
    procedure DoContextMenu(X, Y: Integer; HitTest: TWebHitTest; const Link, Media: string;
      var Handled: Boolean); virtual;
    procedure DoScriptDialog(Dialog: TWebScriptDialog; const Message: string;
      var Input: string; var Accepted: Boolean); virtual;
    { When Editable is true the page can be edited by the user }
    property Editable: Boolean read FEditable write SetEditable default False;
    { ZoomFactor can be used to increase or decrease the size of text or content }
    property ZoomFactor: Double read FZoomFactor write SetZoomFactor stored IsZoomFactorStored;
    { When ZoomTextOnly is true only text is resized by zoom factor }
    property ZoomTextOnly: Boolean read FZoomTextOnly write SetZoomTextOnly default False;
    { When DeveloperTools is true the inspector can be shown and an inspect
      item is added to the context menu }
    property DeveloperTools: Boolean read FDeveloperTools write SetDeveloperTools default False;
    { The folder files are downloaded to. When empty the download folder of
      the user is used. }
    property DownloadFolder: string read FDownloadFolder write FDownloadFolder;
    { OnDownloadStart is invoked before a file is downloaded }
    property OnDownloadStart: TWebDownloadStartEvent read FOnDownloadStart write FOnDownloadStart;
    { OnDownloadProgress is invoked as a download progresses }
    property OnDownloadProgress: TWebDownloadEvent read FOnDownloadProgress write FOnDownloadProgress;
    { OnDownloadFinish is invoked when a download finishes or fails }
    property OnDownloadFinish: TWebDownloadEvent read FOnDownloadFinish write FOnDownloadFinish;
    { OnError is invoked when a load fails }
    property OnError: TWebErrorEvent read FOnError write FOnError;
    { OnContextMenu is invoked when a context menu is about to be shown }
    property OnContextMenu: TWebContextMenuEvent read FOnContextMenu write FOnContextMenu;
    { OnHitTest is invoked when the element under the mouse changes }
    property OnHitTest: TWebHitTestEvent read FOnHitTest write FOnHitTest;
    { OnLoadStatusChange occurs when the loading status changes }
    property OnLoadStatusChange: TNotifyEvent read FOnLoadStatusChange write FOnLoadStatusChange;
    { OnLocationChange occurs when a new uri begins to load or is redirected }
    property OnLocationChange: TNotifyEvent read FOnLocationChange write FOnLocationChange;
    { OnTitleChange occurs when the title of the page changes }
    property OnTitleChange: TNotifyEvent read FOnTitleChange write FOnTitleChange;
    { OnNavigate is invoked before a navigation is followed }
    property OnNavigate: TWebNavigateEvent read FOnNavigate write FOnNavigate;
    { OnProgress is invoked as a load progresses }
    property OnProgress: TWebProgressEvent read FOnProgress write FOnProgress;
    { OnScriptDialog is invoked by javascript alert(), confirm(), and prompt() functions }
    property OnScriptDialog: TWebScriptDialogEvent read FOnScriptDialog write FOnScriptDialog;
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
    { Available is true when the WebKitGTK library is installed }
    class function Available: Boolean;
    { Load content by navigating using a protocol such as http: file: or about: }
    procedure Load(const Uri: string);
    { Load content directly from an html string }
    procedure LoadHtml(const Html: string);
    { Stop a load in progress }
    procedure Stop;
    { Repeat the previously navigated uri request or html load }
    procedure Reload;
    { Insert a snippet of javascript into the page and execute it }
    procedure ExecuteScript(const Script: string);
    { Navigate back one step in history }
    procedure GoBack;
    { Navigate forward one step in history }
    procedure GoForward;
    { Query if it's possible to navigate back one step in history }
    function CanGoBack: Boolean;
    { Query if it's possible to navigate forward one step in history }
    function CanGoForward: Boolean;
    { Navigate back (negative) or forward (positive) a number of steps in history }
    procedure BackOrForward(Steps: Integer);
    { Query if it's possible to navigate back or forward a number of steps in history }
    function BackOrForwardExists(Steps: Integer): Boolean;
    { Show the inspector, which also sets DeveloperTools to true }
    procedure ShowInspector;
    { Close the inspector }
    procedure CloseInspector;
    { Query the title and uri of the page a number of steps back (negative)
      or forward (positive) in history }
    function HistoryItem(Steps: Integer; out Title, Uri: string): Boolean;
    { Download a file to the download folder }
    procedure Download(const Uri: string);
    { Cancel a download which is in progress }
    procedure CancelDownload(Download: TWebDownload);
    { Remove the downloads which are not in progress from the list of downloads }
    procedure ClearDownloads;
    { The folder files are downloaded to, which is the download folder of
      the user unless DownloadFolder is set }
    function ActiveDownloadFolder: string;
    { Show the print dialog for the page }
    procedure Print;
    { Capture an image of the visible page and place it on the clipboard. The
      image is captured in the background and is on the clipboard a moment
      after this method returns. }
    procedure CaptureToClipboard;
    { Add a listener which is notified of changes in the browser }
    procedure AddListener(Listener: TWebNotifyEvent);
    { Remove a listener }
    procedure RemoveListener(Listener: TWebNotifyEvent);
    { The inspector control associated with the browser, or nil if there is
      none. It is set when the WebBrowser property of an inspector control is
      set to the browser. }
    property Inspector: TWebInspector read FInspector;
    { The uri of the link under the mouse }
    property HoverLink: string read FHoverLink;
    { The number of downloads started by the browser }
    property DownloadCount: Integer read GetDownloadCount;
    { The downloads started by the browser, with the oldest first }
    property Downloads[Index: Integer]: TWebDownload read GetDownload;
    { The uri of the content being displayed }
    property Location: string read FLocation write SetLocation;
    { Html stores the last value passed to LoadHtml }
    property Html: string read FHtml;
    { HtmlDefined is true when the last load method invoked was LoadHtml }
    property HtmlDefined: Boolean read FHtmlDefined;
    { The status of the current load }
    property LoadStatus: TWebLoadStatus read FLoadStatus;
    { Loading is true while a load is in progress }
    property Loading: Boolean read GetLoading;
    { The progress of the current load ranging from 0 to 100 }
    property Progress: Integer read FProgress;
    { The title string extracted from a web page }
    property Title: string read FTitle;
  end;

{ TWebBrowser }

  TWebBrowser = class(TCustomWebBrowser)
  published
    property Align;
    property Anchors;
    property BorderSpacing;
    property Constraints;
    property Enabled;
    property Location;
    property Editable;
    property TabOrder;
    property TabStop default True;
    property Visible;
    property ZoomFactor;
    property ZoomTextOnly;
    property DeveloperTools;
    property DownloadFolder;
    property OnDownloadStart;
    property OnDownloadProgress;
    property OnDownloadFinish;
    property OnContextMenu;
    property OnScriptDialog;
    property OnError;
    property OnHitTest;
    property OnLoadStatusChange;
    property OnLocationChange;
    property OnTitleChange;
    property OnNavigate;
    property OnProgress;
  end;

{ TWebInspector is a control which hosts the inspector of a browser.

  When Active is true the inspector of the associated browser is shown inside
  the control rather than in a window of its own.

  Nothing is inspected at design time, where the control paints the WebKit
  logo. It paints the logo and a message if the WebKitGTK library is not
  installed. }

  TWebInspector = class(TWinControl, IWebInspectorEvents)
  private
    FWebBrowser: TCustomWebBrowser;
    FActive: Boolean;
    FClosing: Boolean;
    FCanvas: TControlCanvas;
    procedure WMPaint(var Message: TLMPaint); message LM_PAINT;
    procedure BrowserNotify(Sender: TObject; Notify: TWebNotify);
    { IWebInspectorEvents }
    procedure ViewInspectorClosed;
    procedure UpdateInspector;
    procedure CloseInspector;
    procedure SetActive(Value: Boolean);
    procedure SetWebBrowser(Value: TCustomWebBrowser);
  protected
    class procedure WSRegisterClass; override;
    procedure InitializeWnd; override;
    procedure DestroyWnd; override;
    procedure PaintWindow(DC: HDC); override;
    procedure Paint; virtual;
    procedure Notification(AComponent: TComponent; Operation: TOperation); override;
    { ControlCanvas is used to paint the control when it cannot host an inspector }
    property ControlCanvas: TControlCanvas read FCanvas;
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
  published
    { When Active is true this control shows the inspector of the browser }
    property Active: Boolean read FActive write SetActive default False;
    property Align;
    property Anchors;
    property BorderSpacing;
    property Constraints;
    property Enabled;
    property Visible;
    { The browser to inspect }
    property WebBrowser: TCustomWebBrowser read FWebBrowser write SetWebBrowser;
  end;

implementation

{$r webkit.res}

uses
  Forms, Dialogs, WSLCLClasses,
  Codebot.Interop.WebKit;

{ PaintLogo paints a control which has no web view. The WebKit logo is drawn
  in the center of a dashed frame with an optional caption below it. Missing
  is true when the reason for there being no web view is that the WebKitGTK
  library is not installed. }

var
  Logo: TPicture;

procedure PaintLogo(Canvas: TCanvas; const Rect: TRect; const Caption: string;
  Missing: Boolean);
var
  X, Y: Integer;
begin
  Canvas.Brush.Color := 0;
  Canvas.Pen.Color := clWhite;
  Canvas.Pen.Style := psDash;
  Canvas.Rectangle(Rect);
  if Logo = nil then
  begin
    Logo := TPicture.Create;
    Logo.LoadFromResourceName(HInstance, 'webkit.png');
  end;
  X := (Rect.Left + Rect.Right - Logo.Width) div 2;
  Y := (Rect.Top + Rect.Bottom - Logo.Height) div 2;
  Canvas.Draw(X, Y, Logo.Graphic);
  Canvas.Font.Color := clWhite;
  if Caption <> '' then
    Canvas.TextOut((Rect.Left + Rect.Right - Canvas.TextWidth(Caption)) div 2,
      Y + Logo.Height + 4, Caption);
  if Missing then
    Canvas.TextOut(Rect.Left + 5, Rect.Top + 5, 'The WebKitGTK library is not installed');
end;

{ TCustomWebBrowser }

constructor TCustomWebBrowser.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  ControlStyle := ControlStyle - [csSetCaption];
  Width := 400;
  Height := 400;
  TabStop := True;
  FZoomFactor := 1;
  FDownloads := TList.Create;
end;

{ Downloads in progress are left to complete, and have nothing to notify once
  the web view is destroyed }

destructor TCustomWebBrowser.Destroy;
var
  I: Integer;
begin
  Application.RemoveAsyncCalls(Self);
  for I := 0 to FDownloads.Count - 1 do
    TObject(FDownloads[I]).Free;
  FDownloads.Free;
  inherited Destroy;
end;

class function TCustomWebBrowser.Available: Boolean;
begin
  Result := InitWebKit;
end;

function TCustomWebBrowser.HasView: Boolean;
begin
  Result := (not (csDesigning in ComponentState)) and Available;
end;

procedure TCustomWebBrowser.DestroyWnd;
begin
  FreeAndNil(FCanvas);
  inherited DestroyWnd;
end;

procedure TCustomWebBrowser.WMPaint(var Message: TLMPaint);
begin
  if (csDestroying in ComponentState) or (not HandleAllocated) then
    Exit;
  Include(FControlState, csCustomPaint);
  inherited WMPaint(Message);
  Exclude(FControlState, csCustomPaint);
end;

{ A web view paints itself, so the control is only painted when it has none }

procedure TCustomWebBrowser.PaintWindow(DC: HDC);
var
  Changed: Boolean;
begin
  if HasView then
    Exit;
  if FCanvas = nil then
  begin
    FCanvas := TControlCanvas.Create;
    FCanvas.Control := Self;
  end;
  Changed := (not FCanvas.HandleAllocated) or (FCanvas.Handle <> DC);
  if Changed then
    FCanvas.Handle := DC;
  Paint;
  if Changed then
    FCanvas.Handle := 0;
end;

procedure TCustomWebBrowser.Paint;
begin
  PaintLogo(FCanvas, ClientRect, '', not (csDesigning in ComponentState));
end;

var
  Registered: Boolean;

class procedure TCustomWebBrowser.WSRegisterClass;
begin
  if Registered then
    Exit;
  Registered := True;
  RegisterWSComponent(TCustomWebBrowser, TWSWebBrowser);
end;

{ A web view is created with each window, so the state kept by the control is
  applied to the new web view here }

procedure TCustomWebBrowser.InitializeWnd;
begin
  inherited InitializeWnd;
  FTitle := '';
  FProgress := 0;
  FLoadStatus := lsNone;
  TWSWebBrowser.SetEditable(Self, FEditable);
  TWSWebBrowser.SetZoomTextOnly(Self, FZoomTextOnly);
  TWSWebBrowser.SetZoomFactor(Self, FZoomFactor);
  TWSWebBrowser.SetDeveloperTools(Self, FDeveloperTools);
  if FHtmlDefined then
    TWSWebBrowser.LoadHtml(Self, FHtml)
  else if FLocation <> '' then
    TWSWebBrowser.Load(Self, FLocation);
  Notify(wnReady);
end;

procedure TCustomWebBrowser.Notify(Kind: TWebNotify);
var
  Listeners: TWebNotifyEvents;
  I: Integer;
begin
  { A copy is used as a listener may remove itself when notified }
  Listeners := Copy(FListeners);
  for I := Low(Listeners) to High(Listeners) do
    Listeners[I](Self, Kind);
end;

procedure TCustomWebBrowser.AddListener(Listener: TWebNotifyEvent);
begin
  RemoveListener(Listener);
  SetLength(FListeners, Length(FListeners) + 1);
  FListeners[High(FListeners)] := Listener;
end;

procedure TCustomWebBrowser.RemoveListener(Listener: TWebNotifyEvent);
var
  I, J: Integer;
begin
  for I := Low(FListeners) to High(FListeners) do
    if (TMethod(FListeners[I]).Code = TMethod(Listener).Code) and
      (TMethod(FListeners[I]).Data = TMethod(Listener).Data) then
    begin
      for J := I to High(FListeners) - 1 do
        FListeners[J] := FListeners[J + 1];
      SetLength(FListeners, Length(FListeners) - 1);
      Break;
    end;
end;

{ TCustomWebBrowser.IWebBrowserEvents }

function ContextToHitTest(Context: LongWord): TWebHitTest;
begin
  Result := [];
  if Context and WEBKIT_HIT_TEST_RESULT_CONTEXT_LINK <> 0 then
    Include(Result, htLink);
  if Context and WEBKIT_HIT_TEST_RESULT_CONTEXT_IMAGE <> 0 then
    Include(Result, htImage);
  if Context and WEBKIT_HIT_TEST_RESULT_CONTEXT_MEDIA <> 0 then
    Include(Result, htMedia);
  if Context and WEBKIT_HIT_TEST_RESULT_CONTEXT_SELECTION <> 0 then
    Include(Result, htSelection);
  if Context and WEBKIT_HIT_TEST_RESULT_CONTEXT_EDITABLE <> 0 then
    Include(Result, htEditable);
end;

procedure TCustomWebBrowser.ViewLoadChange(LoadEvent: Integer);
begin
  case LoadEvent of
    WEBKIT_LOAD_STARTED: DoLoadStatus(lsStarted);
    WEBKIT_LOAD_REDIRECTED: DoLoadStatus(lsRedirected);
    WEBKIT_LOAD_COMMITTED: DoLoadStatus(lsCommitted);
    WEBKIT_LOAD_FINISHED: DoLoadStatus(lsFinished);
  end;
end;

procedure TCustomWebBrowser.ViewError(const Uri: string; ErrorCode: Integer;
  const ErrorMessage: string; var Handled: Boolean);
begin
  DoError(Uri, ErrorCode, ErrorMessage, Handled);
end;

procedure TCustomWebBrowser.ViewProgress(Progress: Integer);
begin
  DoProgress(Progress);
end;

procedure TCustomWebBrowser.ViewLocationChange(const Uri: string);
begin
  DoLocationChange(Uri);
end;

procedure TCustomWebBrowser.ViewTitleChange(const Title: string);
begin
  DoTitleChange(Title);
end;

procedure TCustomWebBrowser.ViewNavigate(const Uri: string; var Allow: Boolean);
var
  Action: TWebNavigateAction;
begin
  Action := naAllow;
  DoNavigate(Uri, Action);
  Allow := Action = naAllow;
end;

procedure TCustomWebBrowser.ViewHitTest(Context: LongWord; const Link, Media: string);
begin
  DoHitTest(ContextToHitTest(Context), Link, Media);
end;

procedure TCustomWebBrowser.ViewContextMenu(X, Y: Integer; Context: LongWord;
  const Link, Media: string; var Handled: Boolean);
begin
  DoContextMenu(X, Y, ContextToHitTest(Context), Link, Media, Handled);
end;

procedure TCustomWebBrowser.ViewScriptDialog(Dialog: Integer; const Message: string;
  var Input: string; var Accepted: Boolean);
begin
  case Dialog of
    WEBKIT_SCRIPT_DIALOG_ALERT: DoScriptDialog(sdAlert, Message, Input, Accepted);
    WEBKIT_SCRIPT_DIALOG_CONFIRM: DoScriptDialog(sdConfirm, Message, Input, Accepted);
    WEBKIT_SCRIPT_DIALOG_PROMPT: DoScriptDialog(sdPrompt, Message, Input, Accepted);
  end;
end;

procedure TCustomWebBrowser.DoLoadStatus(Status: TWebLoadStatus);
begin
  if csDestroying in ComponentState then
    Exit;
  { A failed load is followed by a finished status, which is ignored so the
    status remains failed until the next load starts }
  if (Status = lsFinished) and (FLoadStatus = lsFailed) then
    Exit;
  if Status = FLoadStatus then
    Exit;
  FLoadStatus := Status;
  Notify(wnLoadStatus);
  if Assigned(FOnLoadStatusChange) then
    FOnLoadStatusChange(Self);
end;

procedure TCustomWebBrowser.DoError(const Uri: string; ErrorCode: Integer;
  const ErrorMessage: string; var Handled: Boolean);
begin
  if csDestroying in ComponentState then
    Exit;
  DoLoadStatus(lsFailed);
  if Assigned(FOnError) then
    FOnError(Self, Uri, ErrorCode, ErrorMessage, Handled);
end;

procedure TCustomWebBrowser.DoProgress(Progress: Integer);
begin
  if csDestroying in ComponentState then
    Exit;
  if Progress = FProgress then
    Exit;
  FProgress := Progress;
  Notify(wnProgress);
  if Assigned(FOnProgress) then
    FOnProgress(Self, FProgress);
end;

procedure TCustomWebBrowser.DoLocationChange(const Uri: string);
begin
  if csDestroying in ComponentState then
    Exit;
  if (Uri = '') or (Uri = FLocation) then
    Exit;
  { Html loaded from a string is shown at about:blank, which is not a
    location. Any other uri means a link in the html was followed. }
  if FHtmlDefined then
    if Uri = 'about:blank' then
      Exit
    else
      FHtmlDefined := False;
  FLocation := Uri;
  Notify(wnLocation);
  if Assigned(FOnLocationChange) then
    FOnLocationChange(Self);
end;

procedure TCustomWebBrowser.DoTitleChange(const Title: string);
begin
  if csDestroying in ComponentState then
    Exit;
  if Title = FTitle then
    Exit;
  FTitle := Title;
  Notify(wnTitle);
  if Assigned(FOnTitleChange) then
    FOnTitleChange(Self);
end;

procedure TCustomWebBrowser.DoNavigate(const Uri: string; var Action: TWebNavigateAction);
begin
  if csDestroying in ComponentState then
    Exit;
  if Assigned(FOnNavigate) then
    FOnNavigate(Self, Uri, Action);
end;

procedure TCustomWebBrowser.DoHitTest(HitTest: TWebHitTest; const Link, Media: string);
begin
  if csDestroying in ComponentState then
    Exit;
  if Link <> FHoverLink then
  begin
    FHoverLink := Link;
    Notify(wnHover);
  end;
  if Assigned(FOnHitTest) then
    FOnHitTest(Self, HitTest, Link, Media);
end;

procedure TCustomWebBrowser.DoContextMenu(X, Y: Integer; HitTest: TWebHitTest;
  const Link, Media: string; var Handled: Boolean);
begin
  if csDestroying in ComponentState then
    Exit;
  if Assigned(FOnContextMenu) then
    FOnContextMenu(Self, X, Y, HitTest, Link, Media, Handled);
end;

procedure TCustomWebBrowser.DoScriptDialog(Dialog: TWebScriptDialog;
  const Message: string; var Input: string; var Accepted: Boolean);
var
  Handled: Boolean;
begin
  Accepted := False;
  if csDestroying in ComponentState then
    Exit;
  Handled := False;
  if Assigned(FOnScriptDialog) then
    FOnScriptDialog(Self, Dialog, Message, Input, Accepted, Handled);
  if Handled then
    Exit;
  Accepted := True;
  case Dialog of
    sdAlert: MessageDlg('Alert', Message, mtInformation, [mbOK], 0);
    sdConfirm: Accepted := MessageDlg('Confirmation', Message, mtConfirmation,
      [mbYes, mbNo], 0) = mrYes;
    sdPrompt: Accepted := InputQuery('Prompt', Message, Input);
  end;
end;

{ TCustomWebBrowser normal methods }

procedure TCustomWebBrowser.Load(const Uri: string);
const
  Protocols: array[0..3] of string = ('http://', 'https://', 'file://', 'about:');
var
  Found: Boolean;
  S, L: string;
  I: Integer;
begin
  S := Trim(Uri);
  if S = '' then
    S := 'about:blank';
  L := LowerCase(S);
  Found := False;
  for I := Low(Protocols) to High(Protocols) do
    if Pos(Protocols[I], L) = 1 then
    begin
      Found := True;
      Break;
    end;
  if not Found then
    S := 'https://' + S;
  FHtmlDefined := False;
  if HandleAllocated then
    TWSWebBrowser.Load(Self, S);
  if S <> FLocation then
  begin
    FLocation := S;
    Notify(wnLocation);
    if Assigned(FOnLocationChange) then
      FOnLocationChange(Self);
  end;
end;

procedure TCustomWebBrowser.LoadHtml(const Html: string);
begin
  FHtml := Html;
  FHtmlDefined := True;
  if HandleAllocated then
    TWSWebBrowser.LoadHtml(Self, FHtml);
end;

procedure TCustomWebBrowser.Stop;
begin
  if HandleAllocated then
    TWSWebBrowser.Stop(Self);
end;

procedure TCustomWebBrowser.Reload;
begin
  if not HandleAllocated then
    Exit;
  if FHtmlDefined then
    TWSWebBrowser.LoadHtml(Self, FHtml)
  else
    TWSWebBrowser.Reload(Self);
end;

procedure TCustomWebBrowser.ExecuteScript(const Script: string);
begin
  if HandleAllocated then
    TWSWebBrowser.ExecuteScript(Self, Script);
end;

procedure TCustomWebBrowser.GoBack;
begin
  BackOrForward(-1);
end;

procedure TCustomWebBrowser.GoForward;
begin
  BackOrForward(1);
end;

function TCustomWebBrowser.CanGoBack: Boolean;
begin
  Result := BackOrForwardExists(-1);
end;

function TCustomWebBrowser.CanGoForward: Boolean;
begin
  Result := BackOrForwardExists(1);
end;

procedure TCustomWebBrowser.BackOrForward(Steps: Integer);
begin
  if HandleAllocated and (Steps <> 0) then
  begin
    { History only holds pages loaded from a uri }
    FHtmlDefined := False;
    TWSWebBrowser.BackOrForward(Self, Steps);
  end;
end;

function TCustomWebBrowser.BackOrForwardExists(Steps: Integer): Boolean;
begin
  Result := HandleAllocated and TWSWebBrowser.BackOrForwardExists(Self, Steps);
end;

procedure TCustomWebBrowser.ShowInspector;
begin
  DeveloperTools := True;
  if HandleAllocated then
    TWSWebBrowser.ShowInspector(Self, True);
end;

procedure TCustomWebBrowser.CloseInspector;
begin
  if HandleAllocated then
    TWSWebBrowser.ShowInspector(Self, False);
end;

function TCustomWebBrowser.HistoryItem(Steps: Integer; out Title, Uri: string): Boolean;
begin
  Title := '';
  Uri := '';
  Result := HandleAllocated and TWSWebBrowser.HistoryItem(Self, Steps, Title, Uri);
end;

procedure TCustomWebBrowser.Download(const Uri: string);
begin
  if HandleAllocated then
    TWSWebBrowser.Download(Self, Uri);
end;

procedure TCustomWebBrowser.CancelDownload(Download: TWebDownload);
begin
  if (Download <> nil) and (Download.FStatus = dsActive) then
    TWSWebBrowser.CancelDownload(Download.FHandle);
end;

procedure TCustomWebBrowser.ClearDownloads;
var
  Item: TWebDownload;
  I: Integer;
begin
  for I := FDownloads.Count - 1 downto 0 do
  begin
    Item := TWebDownload(FDownloads[I]);
    if Item.FStatus <> dsActive then
    begin
      FDownloads.Delete(I);
      Item.Free;
    end;
  end;
  Notify(wnDownload);
end;

function TCustomWebBrowser.ActiveDownloadFolder: string;
begin
  Result := FDownloadFolder;
  if (Result = '') and Available then
    Result := TWSWebBrowser.DownloadFolder;
  if Result = '' then
    Result := GetUserDir + 'Downloads';
end;

function TCustomWebBrowser.GetDownloadCount: Integer;
begin
  Result := FDownloads.Count;
end;

function TCustomWebBrowser.GetDownload(Index: Integer): TWebDownload;
begin
  Result := TWebDownload(FDownloads[Index]);
end;

function TCustomWebBrowser.FindDownload(Handle: Pointer): TWebDownload;
var
  I: Integer;
begin
  for I := FDownloads.Count - 1 downto 0 do
  begin
    Result := TWebDownload(FDownloads[I]);
    if Result.FHandle = Handle then
      Exit;
  end;
  Result := nil;
end;

{ A file is not written over an existing file. A number is added to its name
  until the name is not in use. }

function UniqueFileName(const FileName: string): string;
var
  Path, Ext: string;
  I: Integer;
begin
  Result := FileName;
  if not FileExists(Result) then
    Exit;
  Ext := ExtractFileExt(FileName);
  Path := Copy(FileName, 1, Length(FileName) - Length(Ext));
  I := 1;
  repeat
    Result := Path + ' (' + IntToStr(I) + ')' + Ext;
    Inc(I);
  until not FileExists(Result);
end;

procedure TCustomWebBrowser.ViewDownloadStart(Download: Pointer; const Uri: string;
  var FileName: string; var Allow: Boolean);
var
  Item: TWebDownload;
  S: string;
begin
  if csDestroying in ComponentState then
  begin
    Allow := False;
    Exit;
  end;
  S := ExtractFileName(FileName);
  if S = '' then
    S := 'download';
  FileName := UniqueFileName(IncludeTrailingPathDelimiter(ActiveDownloadFolder) + S);
  if Assigned(FOnDownloadStart) then
    FOnDownloadStart(Self, Uri, FileName, Allow);
  if (not Allow) or (FileName = '') then
  begin
    Allow := False;
    Exit;
  end;
  ForceDirectories(ExtractFileDir(FileName));
  Item := TWebDownload.Create;
  Item.FHandle := Download;
  Item.FUri := Uri;
  Item.FFileName := FileName;
  FDownloads.Add(Item);
  Notify(wnDownload);
end;

procedure TCustomWebBrowser.ViewDownloadProgress(Download: Pointer; Progress: Integer);
var
  Item: TWebDownload;
begin
  if csDestroying in ComponentState then
    Exit;
  Item := FindDownload(Download);
  if (Item = nil) or (Item.FProgress = Progress) then
    Exit;
  Item.FProgress := Progress;
  Notify(wnDownload);
  if Assigned(FOnDownloadProgress) then
    FOnDownloadProgress(Self, Item);
end;

{ A download which fails is reported as failed and then as finished. The
  download is released after it finishes, so its handle is no longer kept. }

procedure TCustomWebBrowser.ViewDownloadFinish(Download: Pointer; Failed: Boolean;
  const ErrorMessage: string);
var
  Item: TWebDownload;
begin
  if csDestroying in ComponentState then
    Exit;
  Item := FindDownload(Download);
  if Item = nil then
    Exit;
  if Failed then
  begin
    Item.FStatus := dsFailed;
    Item.FErrorMessage := ErrorMessage;
    Exit;
  end;
  Item.FHandle := nil;
  if Item.FStatus = dsActive then
  begin
    Item.FStatus := dsFinished;
    Item.FProgress := 100;
  end;
  Notify(wnDownload);
  if Assigned(FOnDownloadFinish) then
    FOnDownloadFinish(Self, Item);
end;

{ Inspect Element in the context menu opens the inspector. When the browser
  has an inspector control the inspector is shown in it, rather than in a
  window of its own. The control is shown after the request returns. }

procedure TCustomWebBrowser.ViewInspectorRequest(var Hosted: Boolean);
begin
  if (csDestroying in ComponentState) or (FInspector = nil) then
    Exit;
  Hosted := True;
  Application.QueueAsyncCall(InspectorRequestAsync, 0);
end;

{ The inspector control and any hidden containers holding it, such as a
  caption box, are shown before the inspector is made active }

procedure TCustomWebBrowser.InspectorRequestAsync(Data: PtrInt);
var
  Control: TControl;
begin
  if (csDestroying in ComponentState) or (FInspector = nil) then
    Exit;
  Control := FInspector;
  while (Control <> nil) and not (Control is TCustomForm) do
  begin
    Control.Visible := True;
    Control := Control.Parent;
  end;
  if FInspector.Active then
    FInspector.UpdateInspector
  else
    FInspector.Active := True;
end;

{ An inspector control sets itself as the inspector of the browser it is
  associated with. The two are joined by a free notification, so the browser
  is told if the inspector is destroyed. }

procedure TCustomWebBrowser.SetInspector(Value: TWebInspector);
begin
  FInspector := Value;
  if FInspector <> nil then
    FInspector.FreeNotification(Self);
end;

procedure TCustomWebBrowser.Notification(AComponent: TComponent; Operation: TOperation);
begin
  inherited Notification(AComponent, Operation);
  if (Operation = opRemove) and (AComponent = FInspector) then
    FInspector := nil;
end;

procedure TCustomWebBrowser.Print;
begin
  if HandleAllocated then
    TWSWebBrowser.Print(Self);
end;

procedure TCustomWebBrowser.CaptureToClipboard;
begin
  if HandleAllocated then
    TWSWebBrowser.CaptureToClipboard(Self);
end;

function TCustomWebBrowser.GetLoading: Boolean;
begin
  Result := HandleAllocated and TWSWebBrowser.GetLoading(Self);
end;

function TCustomWebBrowser.IsZoomFactorStored: Boolean;
begin
  Result := FZoomFactor <> 1;
end;

procedure TCustomWebBrowser.SetLocation(const Value: string);
begin
  { Nothing is loaded while reading a form, as the window is yet to be
    created and InitializeWnd loads the location }
  if csLoading in ComponentState then
    FLocation := Value
  else
    Load(Value);
end;

procedure TCustomWebBrowser.SetEditable(Value: Boolean);
begin
  if Value = FEditable then
    Exit;
  FEditable := Value;
  if HandleAllocated then
    TWSWebBrowser.SetEditable(Self, FEditable);
end;

procedure TCustomWebBrowser.SetZoomFactor(Value: Double);
begin
  if Value < 0.1 then
    Value := 0.1
  else if Value > 10 then
    Value := 10;
  if Value = FZoomFactor then
    Exit;
  FZoomFactor := Value;
  if HandleAllocated then
    TWSWebBrowser.SetZoomFactor(Self, FZoomFactor);
end;

procedure TCustomWebBrowser.SetZoomTextOnly(Value: Boolean);
begin
  if Value = FZoomTextOnly then
    Exit;
  FZoomTextOnly := Value;
  if HandleAllocated then
    TWSWebBrowser.SetZoomTextOnly(Self, FZoomTextOnly);
end;

procedure TCustomWebBrowser.SetDeveloperTools(Value: Boolean);
begin
  if Value = FDeveloperTools then
    Exit;
  FDeveloperTools := Value;
  if HandleAllocated then
    TWSWebBrowser.SetDeveloperTools(Self, FDeveloperTools);
end;

{ TWebInspector }

constructor TWebInspector.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  ControlStyle := ControlStyle - [csSetCaption];
  Width := 400;
  Height := 200;
end;

destructor TWebInspector.Destroy;
begin
  WebBrowser := nil;
  inherited Destroy;
end;

var
  InspectorRegistered: Boolean;

class procedure TWebInspector.WSRegisterClass;
begin
  if InspectorRegistered then
    Exit;
  InspectorRegistered := True;
  RegisterWSComponent(TWebInspector, TWSWebInspector);
end;

procedure TWebInspector.InitializeWnd;
begin
  inherited InitializeWnd;
  UpdateInspector;
end;

{ The inspector is closed before its window is destroyed, but remains active
  so it is shown again if the window is recreated }

procedure TWebInspector.DestroyWnd;
begin
  CloseInspector;
  FreeAndNil(FCanvas);
  inherited DestroyWnd;
end;

procedure TWebInspector.WMPaint(var Message: TLMPaint);
begin
  if (csDestroying in ComponentState) or (not HandleAllocated) then
    Exit;
  Include(FControlState, csCustomPaint);
  inherited WMPaint(Message);
  Exclude(FControlState, csCustomPaint);
end;

{ The control is only painted when it cannot host an inspector }

procedure TWebInspector.PaintWindow(DC: HDC);
var
  Changed: Boolean;
begin
  if (not (csDesigning in ComponentState)) and TCustomWebBrowser.Available then
    Exit;
  if FCanvas = nil then
  begin
    FCanvas := TControlCanvas.Create;
    FCanvas.Control := Self;
  end;
  Changed := (not FCanvas.HandleAllocated) or (FCanvas.Handle <> DC);
  if Changed then
    FCanvas.Handle := DC;
  Paint;
  if Changed then
    FCanvas.Handle := 0;
end;

procedure TWebInspector.Paint;
begin
  PaintLogo(FCanvas, ClientRect, 'Web Inspector', not (csDesigning in ComponentState));
end;

procedure TWebInspector.Notification(AComponent: TComponent; Operation: TOperation);
begin
  inherited Notification(AComponent, Operation);
  if (Operation = opRemove) and (AComponent = FWebBrowser) then
    FWebBrowser := nil;
end;

procedure TWebInspector.ViewInspectorClosed;
begin
  if not FClosing then
    FActive := False;
end;

{ A browser creates a new web view each time its window is created, and the
  inspector needs to be shown again for the new web view }

procedure TWebInspector.BrowserNotify(Sender: TObject; Notify: TWebNotify);
begin
  if Notify = wnReady then
    UpdateInspector;
end;

procedure TWebInspector.UpdateInspector;
begin
  if (FWebBrowser = nil) or (not FWebBrowser.HandleAllocated) or (not HandleAllocated) then
    Exit;
  if FActive then
  begin
    FWebBrowser.DeveloperTools := True;
    TWSWebInspector.Open(Self, FWebBrowser);
  end
  else
    CloseInspector;
end;

procedure TWebInspector.CloseInspector;
begin
  if (FWebBrowser = nil) or (not FWebBrowser.HandleAllocated) or (not HandleAllocated) then
    Exit;
  FClosing := True;
  try
    TWSWebInspector.Close(Self, FWebBrowser);
  finally
    FClosing := False;
  end;
end;

procedure TWebInspector.SetActive(Value: Boolean);
begin
  if Value = FActive then
    Exit;
  FActive := Value;
  UpdateInspector;
end;

procedure TWebInspector.SetWebBrowser(Value: TCustomWebBrowser);
begin
  if Value = FWebBrowser then
    Exit;
  if FWebBrowser <> nil then
  begin
    CloseInspector;
    FWebBrowser.RemoveListener(BrowserNotify);
    if FWebBrowser.FInspector = Self then
      FWebBrowser.SetInspector(nil);
    FWebBrowser.RemoveFreeNotification(Self);
  end;
  FWebBrowser := Value;
  if FWebBrowser <> nil then
  begin
    FWebBrowser.FreeNotification(Self);
    FWebBrowser.SetInspector(Self);
    FWebBrowser.AddListener(BrowserNotify);
    UpdateInspector;
  end;
end;

finalization
  Logo.Free;
end.
